local:
  prompt_style: "chatml"
  llm_hf_repo_id: NousResearch/Nous-Hermes-2-Mistral-7B-DPO-GGUF
  llm_hf_model_file: Nous-Hermes-2-Mistral-7B-DPO.Q8_0.gguf
  embedding_hf_model_name: BAAI/bge-large-en-v1.5
  local_model_folder: /Users/raj/Temp/llm-models