local:
  prompt_style: "chatml"
  llm_hf_repo_id: TheBloke/Mistral-7B-OpenOrca-GGUF
  llm_hf_model_file: mistral-7b-openorca.Q4_K_M.gguf
  embedding_hf_model_name: BAAI/bge-large-en-v1.5
  local_model_folder: /Users/raj/Temp/llm-models