llm:
  mode: local
  max_new_tokens: 512
  context_window: 8000
  tokenizer: mistralai/Mistral-7B-Instruct-v0.2

local:
  prompt_style: "mistral"
  llm_hf_repo_id: mlabonne/AlphaMonarch-7B-GGUF
  llm_hf_model_file: alphamonarch-7b.Q8_0.gguf
  embedding_hf_model_name: BAAI/bge-large-en-v1.5
  local_model_folder: /Users/raj/Temp/llm-models