local:
  prompt_style: "mistral"
  llm_hf_repo_id: TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF
  llm_hf_model_file: mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf
  embedding_hf_model_name: BAAI/bge-large-en-v1.5